// Code generated by mockery 2.9.4. DO NOT EDIT.

package mocks

import (
	users "absency/business/users"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UserRepoInterface is an autogenerated mock type for the UserRepoInterface type
type UserRepoInterface struct {
	mock.Mock
}

// Login provides a mock function with given fields: domain, ctx
func (_m *UserRepoInterface) Login(domain users.Users, ctx context.Context) (users.Users, error) {
	ret := _m.Called(domain, ctx)

	var r0 users.Users
	if rf, ok := ret.Get(0).(func(users.Users, context.Context) users.Users); ok {
		r0 = rf(domain, ctx)
	} else {
		r0 = ret.Get(0).(users.Users)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(users.Users, context.Context) error); ok {
		r1 = rf(domain, ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
